name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
      - name: Add DigitalOcean to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to DigitalOcean
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DEPLOY_PATH: /var/www/peterchinman.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: |

          ssh root@${{ secrets.DROPLET_IP }} "
            mkdir -p $DEPLOY_PATH/public_html"

          rsync -avz --delete \
            --exclude=".git" \
            --exclude="hapax-finder" \ # hapax-finder lives in same folder, make sure it's not overwritten
            ./ root@${{ secrets.DROPLET_IP }}:$DEPLOY_PATH
          
          # SSH into the server for post-deployment tasks
          ssh root@${{ secrets.DROPLET_IP }} "
            # Install dependencies using Composer
            if [ -f $DEPLOY_PATH/composer.json ]; then
              cd $DEPLOY_PATH
              composer install --no-interaction --no-dev --optimize-autoloader
            fi

            # Set permissions and reload the server
            chown -R www-data:www-data $DEPLOY_PATH && \
            chmod -R 755 $DEPLOY_PATH && \

            # Reload Web Server
            systemctl reload apache2"
